# Usa la imagen oficial de Node.js como base
FROM node:18

# Establece el directorio de trabajo en /usr/src/app
WORKDIR /usr/src/app

# Copia los archivos package.json y package-lock.json al directorio de trabajo
COPY package*.json ./

# Instala las dependencias
RUN npm install && npm install mongoose && npm install cors

# Copia el código fuente de la aplicación al directorio de trabajo
COPY . .

# Expone el puerto 3000, que es el puerto en el que se ejecuta la aplicación Express
EXPOSE 4000

# Comando para iniciar la aplicación
CMD ["node", "app.js"]
